image: node:18

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_COMMIT_BRANCH == "develop"

build-job:
  script:
    - cd frontend
    - npm install --legacy-peer-deps
    - echo "Skipping tests during early development"