image: node:18

# Simple development pipeline
dev-check:
  script:
    # Frontend check
    - cd frontend
    - npm install --legacy-peer-deps
    - echo "Frontend dependencies installed successfully"
    
    # Backend check
    - cd ../backend
    - npm install
    - echo "Backend dependencies installed successfully"
  allow_failure: true  # Won't block development